### PR TITLE
Fix gometalinter

### LINKED ISSUE #7: Cleanup after sync break gometalinter vendored linters
Hi,

I tried to use your tool and it works without any problems with some tools I use (govendor and goveralls) except [gometalinter](https://github.com/alecthomas/gometalinter).

As you can see, they use a `_linters` directory containing the different linters they support. The problem is that directory is cleaned by the [cleanup function called on tool sync](https://github.com/twitchtv/retool/blob/master/sync.go#L45), making gometalinter throwing `gometalinter: error: could not find vendored linters in GOPATH`. 

The only solutions I can see are:
- to disable the vendored linters feature with  `--vendored-linters=false`, but I didn't like because it implies gometalinter to fetch linters without controlling the version
- add a new flag like `retool add --cleaning=false github.com/alecthomas/gometalinter origin/master` which generate something like this
```
{
  "Tools": [
    {
      "Repository": "github.com/alecthomas/gometalinter",
      "Commit": "bae2f1293d092fd8167939d5108d1b025eaef9de",
      "Clean": false
    }
  ]
}
```
- remove the `s.cleanup()` line because who care to have useless files in the `_tools` directory ? It's not supposed to be in the VCS

Is there another solutions ? Can you do something about this ?
Thank you.

### PR DESCRIPTION
**Pull request by spenczar**
Two changes are required:

First, we need to not delete the `github.com/alecthomas/gometalinter/_linters` directory, since it contains the vendored source for gometalinter's linters.

Second, we need to set GOBIN and GOPATH for our `retool do` subcommand. `gometalinter` uses these environment variables to find its vendored linters.

Depends on #14.
Fixes #7.

### CODE REVIEW

File: do.go [hunk 1]
```diff
@@ -16,13 +16,45 @@ func setPath() (unset func()) {
...
 	args := positionalArgs
 	if len(args) == 0 {
 		fatal("no command passed to retool do", nil)
 	}
 
-	defer setPath()()
+	unsetPath := setPath()
+	defer unsetPath()
+
+	unsetGoEnv := setGoEnv()
```
Comment (GarethLewin) [inline do.go]: Why are you un-setting the environment? Surely you are not modifying the parent's environment so when retool is done these changes will be gone? I might be missing something.

Comment (spenczar) [inline do.go]: Yes, this shouldn't be necessary. It's a better-safe-than-sorry thing which is probably overcautious just in case later steps do anything - I wanted some way to say "set some environment variables just for commands I exec in the context of this block."

Maybe worth getting rid of the complexity?

Comment (GarethLewin) [inline do.go]: That was my intuition (getting rid of the complexity).
